# Generated by Django 5.2.7 on 2025-10-13 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncias', '0001_initial'),
        ('localidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entidades_oficiais', to='localidades.cidade')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entidades_oficiais', to='localidades.estado')),
                ('gestores', models.ManyToManyField(limit_choices_to={'tipo_usuario': 'GESTOR_PUBLICO'}, related_name='entidades_gerenciadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entidade Oficial',
                'verbose_name_plural': 'Entidades Oficiais',
            },
        ),
        migrations.CreateModel(
            name='OfficialResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_oficial', to='denuncias.denuncia')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='gestao_publica.officialentity')),
            ],
            options={
                'verbose_name': 'Resposta Oficial',
                'verbose_name_plural': 'Respostas Oficiais',
                'ordering': ['-data_resposta'],
            },
        ),
        migrations.AddConstraint(
            model_name='officialentity',
            constraint=models.UniqueConstraint(fields=('nome', 'cidade', 'estado'), name='entidade_unica_por_localidade'),
        ),
    ]
