# Generated by Django 5.0.7 on 2024-07-25 18:20

from django.db import migrations


def popular_categorias(apps, schema_editor):
    """Popula o banco de dados com categorias iniciais para as denúncias."""
    Categoria = apps.get_model('denuncias', 'Categoria')
    
    categorias = [
        'Iluminação Pública',
        'Saneamento Básico',
        'Buracos na Via',
        'Lixo Acumulado',
        'Transporte Público',
        'Segurança Pública',
        'Manutenção de Praças e Parques',
        'Poluição Sonora',
        'Controle de Pragas Urbanas',
        'Acessibilidade',
        'Outros',
    ]
    
    for nome_categoria in categorias:
        Categoria.objects.get_or_create(nome=nome_categoria)

class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popular_categorias),
    ]