# Generated by Django 5.2.7 on 2025-10-13 18:49

from django.db import migrations

ESTADOS = [
    ('Acre', 'AC'),
    ('Alagoas', 'AL'),
    ('Amapá', 'AP'),
    ('Amazonas', 'AM'),
    ('Bahia', 'BA'),
    ('Ceará', 'CE'),
    ('Distrito Federal', 'DF'),
    ('Espírito Santo', 'ES'),
    ('Goiás', 'GO'),
    ('Maranhão', 'MA'),
    ('Mato Grosso', 'MT'),
    ('Mato Grosso do Sul', 'MS'),
    ('Minas Gerais', 'MG'),
    ('Pará', 'PA'),
    ('Paraíba', 'PB'),
    ('Paraná', 'PR'),
    ('Pernambuco', 'PE'),
    ('Piauí', 'PI'),
    ('Rio de Janeiro', 'RJ'),
    ('Rio Grande do Norte', 'RN'),
    ('Rio Grande do Sul', 'RS'),
    ('Rondônia', 'RO'),
    ('Roraima', 'RR'),
    ('Santa Catarina', 'SC'),
    ('São Paulo', 'SP'),
    ('Sergipe', 'SE'),
    ('Tocantins', 'TO'),
]

def popular_estados(apps, schema_editor):
    """
    Popula a tabela de Estados com os estados do Brasil.
    """
    Estado = apps.get_model('localidades', 'Estado')
    for nome, uf in ESTADOS:
        Estado.objects.create(nome=nome, uf=uf)

def remover_estados(apps, schema_editor):
    """
    Remove todos os estados.
    """
    Estado = apps.get_model('localidades', 'Estado')
    Estado.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popular_estados, reverse_code=remover_estados),
    ]